version: '3.9'

services:
    service:
        container_name: $CONTAINER_NAME
        build:
          context: .
          dockerfile: ./Dockerfile
        ports:
            - "5000:5000"
        env_file:
            - ./.env
        volumes:
            - $CONTAINER_DATA:/data
            - $VERSION_FILE:/VERSION:ro
            - ./app:/smart-seminarian-frontend:ro
